name: lm-toxicity
channels:
  - defaults
dependencies:
  - python=3.8

  - pip
  - pip:
      - click
      - nltk
      - tensorboard
      - tensorboardX
      - google-api-python-client
      - git+git://github.com/thesamuel/transformers@lm-toxicity
      - psaw
      - spacy
      - sqlalchemy
      - torchtext
      - tqdm

  - dask
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pytorch
  - scikit-learn
