name: lm-toxicity
channels:
  - defaults
dependencies:
  - python=3.7
  - pip

  - pip:
      - tensorboard
      - tensorboardX
      - google-api-python-client
      - git+git://github.com/thesamuel/transformers@language-model-toxicity

  - click
  - dask
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pytorch
  - scikit-learn
  - spacy
  - sqlalchemy
  - tqdm

