name: toxicity
channels:
  - defaults
dependencies:
  - python=3.8

  - pip
  - pip:
      - click
      - nltk
      - tensorboard
      - tensorboardX
      - google-api-python-client
      - spacy
      - sqlalchemy
      - tqdm
      - transformers

  - ipython
  - numpy
  - pandas
  - scipy
  - dask
  - jupyter
  - jupyterlab
  - matplotlib
  - scikit-learn
  - seaborn
  - pytorch::pytorch
  - pytorch::torchtext
